// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using myApi.Data;

#nullable disable

namespace myApi.Migrations
{
    [DbContext(typeof(MyApiContext))]
    [Migration("20260909131829_AddRelacionAlmacenProducto")]
    partial class AddRelacionAlmacenProducto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("myApi.Models.Almacen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Almacen");
                });

            modelBuilder.Entity("myApi.Models.AlmacenProducto", b =>
                {
                    b.Property<int>("AlmacenId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fecha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AlmacenId", "ProductoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("AlmacenProducto");
                });

            modelBuilder.Entity("myApi.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnidadDeMedida")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("myApi.Models.AlmacenProducto", b =>
                {
                    b.HasOne("myApi.Models.Almacen", "Almacen")
                        .WithMany("AlmacenProductos")
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("myApi.Models.Producto", "Producto")
                        .WithMany("AlmacenProductos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Almacen");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("myApi.Models.Almacen", b =>
                {
                    b.Navigation("AlmacenProductos");
                });

            modelBuilder.Entity("myApi.Models.Producto", b =>
                {
                    b.Navigation("AlmacenProductos");
                });
#pragma warning restore 612, 618
        }
    }
}
